#!/bin/bash

#              Simple-Blog

# Main bash script for the
#  simple blog repository.


# List Drafts
  function listdrafts {
    echo ""
    echo "Files in Drafts:"
    count=1
    for file in /var/www/okju96.xyz/public_html/posts/drafts/* ; do
      printf "   ${count}: ${file##*/}\n"
      count=$((${count}+1))
    done
    echo ""
  }  
  

  if [ ${1} = "add" ] ; then 

# Adding a post    
    if [ ! -z ${2} ] && [ -z ${3} ] ; then
      posttitle=${2}
    elif [ ! -z ${3} ] ; then
      echo ""
      echo "One post at a time please. Additionally, post titles cannot have spaces in them."
      echo "Dashes are recommended instead (they have SEO benefits over no spaces at all)."
      echo ""
      echo "Please try again."
      echo ""
      exit 0 
    else 
      printf "What would you like to call the post? "
      read posttitle
    fi
      echo $posttitle
      vim $posttitle.md
  elif [ ${1} = "post" ] ; then

# Posting a post
    listdrafts
    printf "Which draft would you like to post? "
    read posttopost
    if [[ ${posttopost} =~ ^[0-9]+$ ]] ; then 
      echo "You entered a number; good for you!"
    fi
    if [[ ! ${posttopost} == *".md"* ]] ; then posttopost=${posttopost}.md ; fi
    echo ${posttopost}

  # Get File
    ptphtml="$(echo ${posttopost} | cut -d "." -f 1).html"
    cp /var/www/okju96.xyz/public_html/posts/drafts/${posttopost} \
       /var/www/okju96.xyz/public_html/posts/drafts/${ptphtml}

  # Convert To HTML
    ptphtml="/var/www/okju96.xyz/public_html/post/drafts/${ptphtml}"
    while read -r line ; do
      echo "${line}"
    done < "${ptphtml}"
    exit 0

# Else
  else echo "This instruction needs an argument."
  fi
